"""empty message

Revision ID: a125071a6af0
Revises: d0675899106d
Create Date: 2018-10-21 14:08:24.289329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a125071a6af0'
down_revision = 'd0675899106d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voting_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('team_emails', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voting_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('is_accepting_entries', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('is_accepting_votes', sa.Boolean(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voting_categorization',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['voting_category.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['voting_entry.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'entry_id')
    )
    op.create_table('voting_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['voting_category.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['voting_entry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voting_vote')
    op.drop_table('voting_categorization')
    op.drop_table('voting_category')
    op.drop_table('voting_entry')
    # ### end Alembic commands ###
