"""empty message

Revision ID: d0675899106d
Revises: bce7462dd205
Create Date: 2018-10-17 12:23:04.018906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0675899106d'
down_revision = 'bce7462dd205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_event', sa.Column('check_in_code', sa.String(length=10), server_default='', nullable=False))
    op.add_column('events_event', sa.Column('check_in_enabled', sa.Boolean(), server_default='0', nullable=True))
    op.add_column('events_event', sa.Column('check_in_rewards', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_event', 'check_in_rewards')
    op.drop_column('events_event', 'check_in_enabled')
    op.drop_column('events_event', 'check_in_code')
    # ### end Alembic commands ###
